services:
  - type: web
    name: ai-code-reviewer-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: ./start.sh
    envVars:
      - key: GEMINI_API_KEY
        value: your-api-key-here
    autoDeploy: true
